### ISSUE TITLE
ImportError: No module named 'queryset'

### ISSUE THREAD

**Issue by liber-tas** [variable/django-rest-framework-queryset#2]
Having installed this with: pip install git+ssh://git@github.com/variable/django-rest-framework-queryset.git, then using "from rest_framework_queryset.queryset import RestFrameworkQuerySet" in a view, I get:

  File "/home/louis/nhla/nhla/apps/state/views.py", line 3, in <module>
    from rest_framework_queryset.queryset import RestFrameworkQuerySet
  File "/home/louis/.virtualenvs/nhla/lib/python3.5/site-packages/rest_framework_queryset/__init__.py", line 3, in <module>
    from queryset import RestFrameworkQuerySet
ImportError: No module named 'queryset'

If I change the line in site-packages/rest_framework_queryset/__init__.py, to:

from rest_framework_queryset.queryset import RestFrameworkQuerySet

it works.

Am I doing something wrong, or is there a problem here?

Very cool module BTW, exactly what I was looking for.

**Comment by variable** [comment]
Hey @liber-tas 

Thank you for raising the issue, I will investigate once I get some free time.

Cheers

James

**Comment by variable** [comment]
Hi there, 

I changed to `from .queryset import RestFrameworkQuerySet` hopefully it fixes your problem. Try installing the latest version `pip install django-rest-framwork-queryset`

```
(playground)Jamess-iMac:django-rest-framework-queryset jameslin$ python
Python 2.7.10 (default, Oct 23 2015, 19:19:21) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from rest_framework_queryset.queryset import RestFrameworkQuerySet
>>>
```
