### ISSUE TITLE
Installation Doesn't Work with pip > 9

### ISSUE THREAD

**Issue by cyface** [variable/django-rest-framework-queryset#5]
Unfortunately, it looks like pip removed the 'download' module, so the setup for this package no longer works with pip > 9:

Collecting django-rest-framework-queryset
  Downloading https://files.pythonhosted.org/packages/3f/32/fdc735f68f5bbc39e04811397945968ceafc990602e32e9a3518d1e48ba7/django-rest-framework-queryset-0.0.15.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/pk/r1t6z50x23x6mnqq7v73k4380000gp/T/pip-install-l0sTbH/django-rest-framework-queryset/setup.py", line 6, in <module>
        from pip.download import PipSession
    ImportError: No module named download

Not sure how best to fix, but it makes this package unable to be installed on newer setups.  Thank you!

**Comment by variable** [comment]
I have uploaded a wheel version, can you please verify to see if it works?

**Comment by cyface** [comment]
It worked for me, thanks!
